### ISSUE TITLE
Cannot run `make installers` when distro-build package is installed.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/distro-build#5]
I already had the distro-build package installed at a global scope, and when I run make installers I now get:

```
...
Resolved "distro-build-lib" via file:///Users/leif/racket/build/catalog-copy
Using cached15029186301502918630127 for git://github.com/racket/distro-build/?path=distro-build-lib
raco pkg install: package is currently installed in a wider scope
  package: distro-build-lib
  installed scope: installation
  given scope: user
make[3]: *** [build-from-catalog] Error 1
make[2]: *** [server-from-base] Error 2
make[1]: *** [server] Error 2
make: *** [installers] Error 2
```

It seems like it should only try to download the package if its not already installed, which would resolve the scope issue.

**Comment by mflatt** [comment]
`make installers` only works in a checkout where `make in-place` has not been run before. See "Building Installers" in "INSTALL.txt".

**Comment by LeifAndersen** [comment]
Ah, okay, that would make sense. Does the default `make` target run `make in-place`?

**Comment by LeifAndersen** [comment]
Mmm...looks like it does. So I guess I will go ahead and close this now. Thanks.
